//
// Created by seres on 19/05/2020.
//

#ifndef DISCORD_BOT_WITH_MODULES_CONFIG_HPP
#define DISCORD_BOT_WITH_MODULES_CONFIG_HPP

#define TOKEN "NTY1NTQwODc5NzcxNjMxNjM3.XrCTZw.A8UoQUy_IjXUO08y76vrYgG6MWM"

#endif //DISCORD_BOT_WITH_MODULES_CONFIG_HPP
